stages:
    - deploy

deploy_to_server:
    stage: deploy
    script:
        - apk update # Install necessary packages if required
        - apk add openssh-client sshpass # Install SSH client and sshpass
        # - echo -e "StrictHostKeyChecking no\n" >> ~/.ssh/config # Disable strict host key checking
        - ssh-keyscan -H $SERVER_HOST >> ~/.ssh/known_hosts # Add host to known hosts
        - echo $SSH_PORT
        - echo $$SSH_PASSWORD
        - echo $$SERVER_USERNAME
        - sshpass -p "$SSH_PASSWORD" ssh -p $SSH_PORT $SERVER_USERNAME@$SERVER_HOST 'cd /opt/nodejs-ticketing-software && git pull gitlab master'
        - sshpass -p "$SSH_PASSWORD" ssh -p $SSH_PORT $SERVER_USERNAME@$SERVER_HOST 'export PATH="/root/.nvm/versions/node/v16.20.2/bin:$PATH" && cd /opt/nodejs-ticketing-software && npm install && pm2 restart server'
    only:
        - master
