name: Node.js App Deployment

on:
    push:
        branches:
            - master

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2

            - name: Install Node.js and NPM
              uses: actions/setup-node@v2
              with:
                  node-version: 16

            - name: Install Dependencies
              run: |
                  npm install -g pm2 # Install PM2 globally
                  npm install
            - name: Debug PATH Variable
              run: echo $PATH

            - name: Deploy to Server
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.SERVER_HOST }}
                  username: ${{ secrets.SERVER_USERNAME }}
                  password: ${{ secrets.SSH_PASSWORD }}
                  port: ${{ secrets.SSH_PORT }}
                  script: |
                      cd /opt/nodejs-ticketing-software
                      git pull origin master
                      echo $PATH
                      whoami
                      npm install
                      pm2 restart server
